### ISSUE TITLE
Ethereum oracle script

### ISSUE THREAD

**Issue by gophereth** [ArableProtocol/arablevalidator#10]
- Uniswap ETH/USDT LP token price
- Curve DAI/USDC/USDT LP token CRV reward rate
- Sushiswap ETH/TRU LP token SUSHI / TRU reward rate
- Aave USDT lending reward rate

Can ask each community how to do it safely - Uniswap, Curve, Sushiswap, Aave communities.

**Comment by Abhishekkochar** [comment]
Hi @gophereth,

This task has been done. Pls check the branch ethPolyProtocol.

Cheers,
Abhishek
