### ISSUE TITLE
Raydium oracle script - Solana

### ISSUE THREAD

**Issue by gophereth** [ArableProtocol/arablevalidator#2]
- Raydium RAY/SOL liquidity mining reward info in RAY
- RAY/SOL LP token price
- RAY/USDT liquidity mining reward in RAY
- RAY/USDT LP token price

Can ask Raydium community how to do it safely (should try to avoid the api services as much as possible and should be using decentralized network of chain nodes for security)

**Comment by craastad** [comment]
Current progress is here: https://github.com/ArableProtocol/arablevalidator/pull/13

Issues:

* No clear way to (accurately) to compute LP token price from the given [pool information](https://github.com/ArableProtocol/arablevalidator/blob/fbac04aa520bdfe67672aae65a8d7f948f154318/oracle/collector/solana/raydium/lib/raydium.js#L86) to match [/pairs api](https://api.raydium.io/pairs) is computed
* No explanation from Raydium team on how [/pairs](https://api.raydium.io/pairs) `lp_price` is computed, closed source
* Not sure how reward is computed or represented. There might be clues from decoding raydium-ui calls to [/market](https://api.raydium.io/cache/rpc/market) or [/amm](https://api.raydium.io/cache/rpc/amm). Is this APY?
