### ISSUE TITLE
Fantom oracle script

### ISSUE THREAD

**Issue by hsouf** [ArableProtocol/arablevalidator#26]

**Comment by hsouf** [comment]
Top liquidity pools on **Curve**  (https://ftm.curve.fi/): 
 - 2pool (DAI+USDC)  APY: 1.28% --->rewards? CRV & wFTM-->rewards tokens APR( 2.13% & 4.02%)
 - tricrypto(fUSDT,wBTC, ETH) APY: 3.36%  --->rewards? CRV & wFTM--> rewards tokens APR( 5.75% & 7.99%)

**Comment by gophereth** [comment]
- [ ] Let's do SpookySwap's FTM-BOO and USDC-FTM pair - since it's MVP we can select only two farms and one platform

**Comment by hsouf** [comment]
Ok
