### ISSUE TITLE
Coingecko price relay script

### ISSUE THREAD

**Issue by gophereth** [ArableProtocol/arablevalidator#4]
Fetch specific coins' balance from coingecko 1-2 hrs interval (this shouldn't be closed though) and call a smart contract function to update on-chain price info.  There's rate limit on coingecko, and it is need to fetch this on a single call

Required coins to fetch

- BNB
- SUSHI
- SOL
- OSMO
- CAKE
- QUICK
- CRV
- RAY
- DOT
- TRU

Here's coingecko API to get AVAX price
```
const avaxGeckoId = `avalanche-2`;
const loadAvaxPrice = async () => {
			try {
				const response = (
					await axios.get(`https://api.coingecko.com/api/v3/simple/price?ids=${avaxGeckoId}&vs_currencies=usd`)
				).data;
				setState(prev => ({
					...prev,
					price: parseEther(String(response[avaxGeckoId].usd)),
				}));
			} catch (error) {
				console.error(error);
				setState(prev => ({ ...prev, price: ZERO }));
			}
};
```

Here, you can get coingecko's coin id for each token
https://api.coingecko.com/api/v3/coins/list

**Comment by Abhishekkochar** [comment]
Hi @gophereth,

Can you provide me with the smart contract address this script should call? 
Also, I have set the running time at 1st second of every hour. This job will be running 24 times a day.

Cheers,
Abhishek
