### ISSUE TITLE
Quickswap oracle script - Polygon

### ISSUE THREAD

**Issue by gophereth** [ArableProtocol/arablevalidator#5]
- Quickswap ETH/USDC liquidity mining reward info in QUICK
- Quickswap ETH/USDC LP token price
- Quickswap ETH/QUICK liquidity mining reward info in QUICK
- Quickswap ETH/QUICK LP token price

Can ask Quickswap community how to do it safely (should try to avoid the api services as much as possible and should be using decentralized network of chain nodes for security)

**Comment by Abhishekkochar** [comment]
Hi @gophereth,

This script is working fine except for the reward mechanism. I will work on that this evening. Except this everything else is working fine.

Cheers,
Abhishek
