### ISSUE TITLE
Osmosis oracle script

### ISSUE THREAD

**Issue by gophereth** [ArableProtocol/arablevalidator#9]
- Osmosis OSMO staking reward rate
- Osmosis ATOM/OSMO LP token price
- Osmosis ATOM/OSMO liquidity mining reward rate

Can ask Osmosis community how to do it safely (should try to avoid the api services as much as possible and should be using decentralized network of chain nodes for security)

**Comment by craastad** [comment]
I asked a [clarifying question](https://discord.com/channels/798583171548840026/877743338760069141/918258262481195098) for pulling data from chain in Osmosis discord

As an MVP, I should be able to compute ATOM/OSMO LP token price from this API:
https://api-osmosis.imperator.co/pools/v1/1

**Comment by goeth121** [comment]
> I asked a [clarifying question](https://discord.com/channels/798583171548840026/877743338760069141/918258262481195098) for pulling data from chain in Osmosis discord
> 
> As an MVP, I should be able to compute ATOM/OSMO LP token price from these APIs: https://api-osmosis.imperator.co/pools/v1/1 https://lcd-osmosis.keplr.app/osmosis/gamm/v1beta1/pools/1

Cool. it sounds good

**Comment by craastad** [comment]
@gophereth

OSMO staking reward rate is ~821,917.808 OSMO per epoch/day with 25% to staking validators. The 100 validators are [here](https://wallet.keplr.app/#/osmosis/stake). Doing research I could not figure out how to programmatically get the reward rate or even which block it's distributed. How do we intend to use the reward rate? Do we want to query it from a particular validator (ideally with low commission)?
